---
- name: Reload iptables
  ansible.builtin.command: netfilter-persistent reload
  become: true
  changed_when: true

- name: Restart docker
  listen: Reload iptables
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: true

- name: Restart fail2ban
  listen: Reload iptables
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
  become: true
