server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log

  - job_name: dnsmasq
    static_configs:
    - targets:
        - localhost
      labels:
        job: dnsmasq-leases
        __path__: /var/log/dnsmasq.leases

  - job_name: journald
    journal:
      labels:
        job: systemd-journal
      path: /var/log/journal
    relabel_configs:
      - source_labels:
        - '__journal__systemd_unit'
        target_label: 'unit'
      - source_labels:
        - '__journal__hostname'
        target_label: 'host'
      - source_labels:
        - __journal_container_name
        target_label: container_name
