---
- name: Restart crio
  become: true
  ansible.builtin.systemd:
    name: crio
    state: reloaded
    enabled: true

- name: Systemctl enable init_task
  listen: Enable init_task
  become: true
  ansible.builtin.systemd:
    name: init_task
    enabled: true
    state: started
    daemon_reload: true

- name: Run startup.sh
  listen: Enable init_task
  become: true
  ansible.builtin.command:
    cmd: /var/init_task/startup.sh
  changed_when: true

- name: Load sysctl
  become: true
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: true

- name: Load overlay module
  listen: Load modules
  become: true
  ansible.builtin.command:
    cmd: modprobe overlay
  changed_when: true

- name: Load br_netfilter module
  listen: Load modules
  become: true
  ansible.builtin.command:
    cmd: modprobe br_netfilter
  changed_when: true
