---
- name: Restart sevpn
  ansible.builtin.shell:
    cmd: |
      docker compose -f /var/sevpn/compose.yml down
      docker compose -f /var/sevpn/compose.yml up -d
    chdir: /var/sevpn
  changed_when: true
