---
- name: Restart sevpn
  become: true
  ansible.builtin.systemd:
    name: vpnserver
    state: restarted
    enabled: true

- name: Apply netplan
  become: true
  ansible.builtin.command:
    cmd: netplan apply
  async: 45
  poll: 0
  changed_when: true
  notify: Restart sevpn
