#cloud-config
# yaml-language-server: $schema=https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/schema-cloud-config-v1.json
hostname: "{{ item.name }}"
manage_etc_hosts: true
fqdn: "{{ item.name }}"
chpasswd:
  list: |
    ubuntu:password
    ansible_user:password
  expire: False
users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEtMsUY0MRNGCYCQ0PPm7XprDdTZgK6C6PyjhPVktTLZ"
  - name: ansible_user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    lock_passwd: false
    shell: /bin/bash
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEtMsUY0MRNGCYCQ0PPm7XprDdTZgK6C6PyjhPVktTLZ"
package_upgrade: true
