---
- name: Subaru templates
  ansible.builtin.import_tasks: templates.yml
  when: ansible_hostname == "souzou08"
- name: Subaru cloudinit
  ansible.builtin.import_tasks: cloudinit.yml
- name: Make subaru
  ansible.builtin.import_tasks: subaru.yml
