---
- name: Make kubernetes.repo
  become: true
  ansible.builtin.template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: "0644"

- name: Install kubelet kubeadm kubectl
  become: true
  ansible.builtin.dnf:
    name:
      - containerd
      - kubelet
      - kubeadm
      - kubectl
      - containernetworking-plugins
    state: present

- name: Mkdir /etc/continerd
  become: true
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Make /etc/containerd/config.toml
  become: true
  ansible.builtin.template:
    src: containerd-config.toml
    dest: /etc/containerd/config.toml
    mode: "0644"
  notify:
    - Restart containerd

- name: Enable kubelet
  become: true
  ansible.builtin.systemd:
    name: kubelet
    enabled: true

- name: Make /etc/sysctl.d/99-kubernetes.conf
  become: true
  ansible.builtin.template:
    src: 99-kubernetes.conf
    dest: /etc/sysctl.d/99-kubernetes.conf
    mode: "0644"
  notify:
    - Load sysctl

- name: Make /etc/modules-load.d/k8s.conf
  become: true
  ansible.builtin.template:
    src: k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    mode: "0644"
  notify:
    - Load modules

- name: Template init_task.service
  become: true
  ansible.builtin.template:
    src: init_task.service
    dest: /etc/systemd/system/init_task.service
    owner: root
    group: root
    mode: "0644"
    backup: true
  notify: Enable init_task

- name: Make init_task dir
  become: true
  ansible.builtin.file:
    path: /var/init_task
    state: directory
    owner: root
    group: root
    mode: "0755"
  notify: Enable init_task

- name: Template startup.sh
  become: true
  ansible.builtin.template:
    src: startup.sh
    dest: /var/init_task/startup.sh
    owner: root
    group: root
    mode: "0755"
    backup: true
  notify: Enable init_task

- name: Template shutdown.sh
  become: true
  ansible.builtin.template:
    src: shutdown.sh
    dest: /var/init_task/shutdown.sh
    owner: root
    group: root
    mode: "0755"
    backup: true
  notify: Enable init_task
