---
- name: Mkdir /var/sevpn
  become: true
  ansible.builtin.file:
    path: /var/sevpn
    state: directory
    mode: "0777"

- name: Make compose.yml
  ansible.builtin.template:
    src: compose.yml
    dest: /var/sevpn/compose.yml
    mode: "0644"
  notify: Restart sevpn
