---
- name: Mkdir /var/sevpn/dnsmasq
  become: true
  ansible.builtin.file:
    path: /var/sevpn/dnsmasq
    state: directory
    mode: "0777"

- name: Make compose.yml
  ansible.builtin.template:
    src: compose.yml
    dest: /var/sevpn/compose.yml
    mode: "0644"
  notify: Restart sevpn

- name: Make Dockerfile
  ansible.builtin.template:
    src: Dockerfile
    dest: /var/sevpn/Dockerfile
    mode: "0644"
  notify: Restart sevpn

- name: Make dnsmasq/*
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/sevpn/dnsmasq/{{ item | basename }}"
    mode: "0644"
  with_fileglob:
    - "./templates/dnsmasq/*"
  notify: Restart sevpn
