---
- name: Mkdir /var/prometheus
  become: true
  ansible.builtin.file:
    path: /var/prometheus/blackbox_exporter
    state: directory
    mode: "0755"

- name: Make prometheus.yml
  become: true
  ansible.builtin.template:
    src: prometheus.yml
    dest: /var/prometheus/prometheus.yml
    mode: "0644"
  notify: Restart prometheus

- name: Make compose.yml
  become: true
  ansible.builtin.template:
    src: compose.yml
    dest: /var/prometheus/compose.yml
    mode: "0644"
  notify: Restart prometheus

- name: Make blackbox_exporter/config.yml
  become: true
  ansible.builtin.template:
    src: blackbox.yml
    dest: /var/prometheus/blackbox_exporter/config.yml
    mode: "0644"
  notify: Restart prometheus

- name: Mkdir /var/prometheus/loki
  become: true
  ansible.builtin.file:
    path: /var/prometheus/loki
    state: directory
    mode: "0755"

- name: Make loki/local-config.yaml
  become: true
  ansible.builtin.template:
    src: loki.yaml
    dest: /var/prometheus/loki/local-config.yaml
    mode: "0644"
  notify: Restart prometheus

- name: Make loki_data
  become: true
  ansible.builtin.file:
    path: /var/prometheus/loki_data
    state: directory
    mode: "0777"

- name: Mkdir /var/prometheus/promtail
  become: true
  ansible.builtin.file:
    path: /var/prometheus/promtail
    state: directory
    mode: "0755"

- name: Make promtail/config.yml
  become: true
  ansible.builtin.template:
    src: promtail.yml
    dest: /var/prometheus/promtail/config.yml
    mode: "0644"
  notify: Restart prometheus
