---
- name: Apt-get update
  become: true
  ansible.builtin.apt:

- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx

- name: Make sites-available/default
  become: true
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  notify: Restart nginx
