---
- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: Update apt
  become: true
  ansible.builtin.apt:
  when: ansible_pkg_mgr == "apt"

- name: Create directory for apt key
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: ansible_pkg_mgr == "apt"

- name: Check Docker GPG key
  become: true
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.asc
  register: docker_gpg_key
  when: ansible_pkg_mgr == "apt"

- name: Download the Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: "{{ docker_gpg_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: not docker_gpg_key.stat.exists

- name: Add Docker repository to Apt sources
  become: true
  ansible.builtin.template:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
  register: docker_repo
  when: ansible_pkg_mgr == "apt"

- name: Update apt
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: ansible_pkg_mgr == "apt" and docker_repo.changed

- name: Install yum-utils
  become: true
  ansible.builtin.dnf:
    name: yum-utils
  when: ansible_pkg_mgr == "yum"

- name: Add Docker repository to Yum sources
  become: true
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    baseurl: https://download.docker.com/linux/rhel/docker-ce.repo
  when: ansible_pkg_mgr == "yum"

- name: Install Docker
  become: true
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable Docker
  become: true
  ansible.builtin.service:
    name: docker
    enabled: true

- name: Docker SDK for Python
  become: true
  ansible.builtin.apt:
    name: python3-docker
    state: present
