---
all:
  vars:
    ansible_user: ansible_user
    ansible_python_interpreter: /usr/bin/python3
  children:
    cloud:
      vars:
        ansible_ssh_common_args: -F ./ssh_config
      children:
        vpnep:
          hosts:
            halcyon-srv.shiron.dev:
    pve:
      vars:
        ansible_ssh_common_args: -F ./ssh_config -o ProxyCommand="ssh -F ./ssh_config ansible_user@halcyon-srv.shiron.dev -W %h:%p"
      children:
        souzou08:
          hosts:
            192.168.30.31:
        souzou03:
          hosts:
            192.168.30.31:
        souzou04:
          hosts:
            192.168.30.31:
        souzou05:
          hosts:
            192.168.30.34:
          vars:
            MINFANA_VMID: 103
