---
all:
  vars:
    ansible_user: ansible_user
    ansible_python_interpreter: /usr/bin/python3
  children:
    vpnep:
      vars:
        ansible_ssh_common_args: -F ./ssh_config
      children:
        vpnep:
          hosts:
            halcyon-srv.shiron.dev:
