---
all:
  vars:
    ansible_user: ansible_user
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: -F ./ssh_config
  children:
    cloud:
      children:
        vpnep:
          hosts:
            halcyon-srv.shiron.dev:
    pve:
      children:
        souzou08:
          hosts:
            192.168.30.31:
        souzou03:
          hosts:
            192.168.30.32:
        souzou04:
          hosts:
            192.168.30.33:
        souzou05:
          hosts:
            192.168.30.34:
          vars:
            MINFANA_VMID: 103
    subaru:
      children:
        subaru01:
          hosts:
            192.168.30.101:
        subaru02:
          hosts:
            192.168.30.102:
        subaru03:
          hosts:
            192.168.30.103:
        control:
          hosts:
            subaru01:
