---
- name: Proxmox
  hosts: pve
  roles:
    - role: pve_setup
      tags:
        - pve_setup

    - role: telegraf
      tags:
        - telegraf

- name: Minfana
  hosts: souzou05
  roles:
    - role: pve_cron
      tags:
        - pve_cron

- name: Pve subaru setup
  hosts: pve_subaru
  roles:
    - role: pve_subaru
      tags:
        - pve_subaru
