---
- name: VPNEP
  hosts: vpnep
  roles:
    - role: fail2ban
      tags:
        - fail2ban
    - role: docker
      tags:
        - docker
    - role: sevpn
      tags:
        - sevpn
    - role: dnsmasq
      tags:
        - dnsmasq
    - role: iptables
      tags:
        - iptables
    - role: prometheus
      tags:
        - prometheus
