name: Main CI

on:
  pull_request:
    branches:
      - main

jobs:
  check-symlinks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find symlinks
        run: |
          if [ -n "$(find . -type l)" ]; then
            echo "Error: Found symbolic links in the repository"
            exit 1
          fi
